---
all:
  children:
    frontend:
      hosts:
        opennebula-node:
          ansible_host: <IP_DE_VOTRE_VM>
          ansible_connection: ssh
    
    node:
      hosts:
        opennebula-node:
          ansible_host: <IP_DE_VOTRE_VM>
          ansible_connection: ssh
