---
all:
  vars:
    #ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_ssh_common_args: '-vvv -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa'
    env_name: aio
    ansible_user: ansible
    ansible_become: true
    ensure_keys_for: [ansible, root]

    one_version: '7.0'
    one_token: oneadmin:N3twork!
    #one_vip: 192.168.1.105
    #one_vip_cidr: 24
    #one_vip_if: eth0

    ds:
      mode: ssh

    vn:
      admin_net:
        managed: true
        template:
          VN_MAD: bridge
          PHYDEV: eth1
          BRIDGE: br0
          AR:
            TYPE: IP4
            IP: 192.168.1.150
            SIZE: 50
          NETWORK_ADDRESS: 192.168.1.0
          NETWORK_MASK: 255.255.255.0
          GATEWAY: 192.168.1.1
          DNS: 1.1.1.1

frontend:
  hosts:
    one-aio:
      ansible_host: 192.168.1.105

node:
  hosts:
    one-aio:
      ansible_host: 192.168.1.105
