---
- hosts: node
  become: true

  tasks:
    - name: Ensure netplan is installed on Debian/Ubuntu (nodes only)
      ansible.builtin.apt:
        name: netplan.io
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"
